### ISSUE TITLE
zip argument #2 must support iteration

### ISSUE THREAD

**Issue by agiani99** [Jonas-Verhellen/argenomic#7]
Sorry again.

Traceback (most recent call last):
  File "illuminate.py", line 74, in <module>
    illumination(omegaconf.OmegaConf.load(configuration.configuration_file))(configuration.generations)
  File "illuminate.py", line 27, in __call__
    self.initial_population()
  File "illuminate.py", line 41, in initial_population
    molecules, descriptors, fitnesses = self.process_molecules(molecules)
  File "illuminate.py", line 57, in process_molecules
    descriptors = list(map(self.descriptor, molecules))
  File "/home/zaliani/sw/argenomic/argenomic/mechanism.py", line 37, in __call__
    for property, range in zip(self.properties, self.ranges):
TypeError: zip argument #2 must support iteration

Here the used config:
[config_az.txt](https://github.com/Jonas-Verhellen/Argenomic/files/4981682/config_az.txt)

Best regards and thx for patience
Andrea

**Comment by Jonas-Verhellen** [comment]
You have forgotten to correctly format your config file. Ranges has to be on the same depth as properties. 
Please check your work extensively before submitting an issue. I will close this issue now.
